name: Build on Windows

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      PYTHON_UNBUFFERED: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        working-directory: ./backend
        run: pip install -r requirements.txt

      - name: Run PyInstaller
        working-directory: ./backend
        run: |
          pyinstaller --onefile --name script --distpath ../frontend/resources src/main.py

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          npm ci

      - name: Create resources/downloads folder
        run: New-Item -ItemType Directory -Force -Path frontend\resources\downloads

      - name: Build Electron (Windows)
        working-directory: ./frontend
        run: |
          npm run build --win

      - name: Upload Windows installer
        uses: actions/upload-artifact@v4.6.2
        continue-on-error: true
        with:
          name: build-test
          path: |
            frontend/dist/*.exe              
            frontend/dist/*.msi
          if-no-files-found: error
          retention-days: 1
          compression-level: 6
          overwrite: true
          include-hidden-files: false
      
      - name: Create Github Release
        if: always()
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: windows-build-${{ github.run_number }}
          release_name: Windows Build ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        if: always()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            frontend/dist/*.exe
            frontend/dist/*.msi
          asset_name: installer-${{ github.run_number }}.zip
          asset_content_type: application/zip
